# Generated by Django 2.2 on 2019-08-29 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeresponsavel', models.CharField(max_length=200)),
                ('cpfresponsavel', models.IntegerField(max_length=11)),
                ('nomecandidato', models.CharField(max_length=200)),
                ('cpfcandidato', models.IntegerField(max_length=11)),
                ('datanascimento', models.DateField()),
                ('endereco', models.CharField(max_length=200)),
                ('endereco_bairro', models.CharField(max_length=200)),
                ('endereco_cidade', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=200)),
                ('docidentificacao', models.CharField(max_length=20)),
                ('docidentificacao_emissor', models.CharField(max_length=50)),
                ('opcaoinscricao', models.CharField(max_length=10)),
                ('em_7_portugues', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('em_8_portugues', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('em_9_portugues', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('em_7_matematica', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('em_8_matematica', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('em_9_matematica', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('em_7_historia', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('em_8_historia', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('em_9_historia', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('em_7_geografia', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('em_8_geografia', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('em_9_geografia', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('em_7_ciencias', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('em_8_ciencias', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('em_9_ciencias', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('provao_portugues', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('provao_matematica', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('provao_historia', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('provao_geografia', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('provao_ciencias', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('encceja_portugues', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('encceja_matematica', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('encceja_historia', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('encceja_geografia', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('encceja_ciencias', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('enem_linguagens', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('enem_matematica', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('outros_portugues', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('outros_matematica', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('outros_historia', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('outros_geografia', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('outros_ciencias', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('media', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuarioinseriu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
