# Generated by Django 2.2 on 2019-08-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0002_auto_20190828_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='nomemae',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='nomepai',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
